### ISSUE TITLE
Internal Server Error on using PNG files

### ISSUE THREAD

**Issue by pratik-choudhari** [HarshKapadia2/one-or-two#10]
**500 Internal Server Error** in /predict when a PNG file is uploaded.

**Comment by pratik-choudhari** [comment]
Reason: PNG files have shape (n, m, 4) whereas in model.py reshape dimensions are (224, 224, 3)
Solution: modify  `image = Image.open(pic_path)` in __model.py__ to `image = Image.open(pic_path).convert('RGB')`

**Comment by HarshKapadia2** [comment]
Hey @pratik-choudhari, thank you so much for raising the issue and following up on it!
Would you be interested in making a PR to resolve that?

**Comment by pratik-choudhari** [comment]
Sure!
