### ISSUE TITLE
Disable `Predict` button on click.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/one-or-two#12]
On the home page (`./templates/home-page.html`), once the `Predict` button is clicked, it should be disabled so that multiple requests are not sent to the server.

Use client side JavaScript (JS) to handle this.

Steps:
- Add an `id` to the `Predict` button in `./templates/home-page.html`.
- Create a new JS file at `./static/js`.
- Include it in the [`{% block head %}`](https://flask.palletsprojects.com/en/1.1.x/patterns/templateinheritance/#:~:text=block%20head) section of `./templates/home-page.html` ([example](https://github.com/HarshKapadia2/attendance_management/blob/v2/student/templates/dashboard.html#:~:text=block%20Head)) after adding `{% block head %}{% endblock %}` to `./templates/base.html` ([example](https://github.com/HarshKapadia2/attendance_management/blob/v2/student/templates/student/base.html#:~:text=block%20head)).
- In the new JS file
   - Refer to the `Predict` button using `const <element> = document.querySelector("#<element-id>")`.
   - Add an event listener with a `click` event to the button.
   - In the event listener, use `<element>.disabled = true` to disable the button.

**Comment by Haroonchik** [comment]
@HarshKapadia2 I will do this task.

**Comment by HarshKapadia2** [comment]
Go ahead @Haroonchik.
Please take note of the suggestions on PRs and commit messages that I gave you in PR #15.

**Comment by Haroonchik** [comment]
@HarshKapadia2 Check, please  https://github.com/HarshKapadia2/one-or-two/pull/17

**Comment by HarshKapadia2** [comment]
PR #17 merged!

**Comment by HarshKapadia2** [comment]
Hey @Haroonchik, I am hosting a Hacktoberfest and Open Source session tomorrow. If you're interested, registration and further details are available here: https://bit.ly/otcHacktoberfest1
