### ISSUE TITLE
Move internal CSS to an external file.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/one-or-two#8]
- `./templates/github-corner.html` has CSS in `<style></style>` tags.
- Remove the `<style>` tag and add the CSS code within it to a new file `./static/css/github-corner.css`.
- Add a link to the `github-corner.css` file in `./templates/base.html`.

**Comment by clairecharles** [comment]
Hey @HarshKapadia2 would love to take this on

**Comment by HarshKapadia2** [comment]
Go ahead, @claire-me!

**Comment by clairecharles** [comment]
Kk

**Comment by clairecharles** [comment]
Hey, @HarshKapadia2 should I add the link of the external CSS `./static/css/github-corner.css` to the `./templates/css/github-corner.html`

**Comment by HarshKapadia2** [comment]
No, please add it only to `./templates/base.html` as mentioned in the 3rd point of the original comment.

**Comment by clairecharles** [comment]
Hey, @HarshKapadia2 just made the pull request please check it out
