### ISSUE TITLE
CSS code splitting.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/one-or-two#9]
- Split the CSS code in `./static/css/style.css` into a file for each page.

## Changes
- Add the CSS code common to all stylesheets to `./static/css/base.css`.
- Add the CSS code pertaining to a particular HTML template file to a new CSS file with the same name as the HTML file, to the `./static/css` dir.
- Delete the `./static/css/style.css` file.
- Remove the link to `style.css` in the `./templates/base.html` file.
- Add a link to the `./static/css/base.css` file to the `./templates/base.html` file as follows

```html
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
```

- In each HTML file, add a link to its specific css file in the [`{% block head %}` block](https://flask.palletsprojects.com/en/1.1.x/patterns/templateinheritance/#:~:text=block%20head).
   - Add a `{% block head %}{% endblock %}` in the `head` of `./templates/base.html` as well.

Eg:
`base.html` ([Example from another project](https://github.com/HarshKapadia2/attendance_management/blob/v2/student/templates/student/base.html#:~:text=block%20head))

```html
<head>
	...
	...
	{% block head %}{% endblock %}
	...
	...
</head>
```

`file-name.html` ([Example from another project](https://github.com/HarshKapadia2/attendance_management/blob/v2/student/templates/dashboard.html#:~:text=block%20Head))

```html
{% extends 'base.html' %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/file-name.css') }}">
{% endblock %}

{% block body %} ...
```

**Comment by Haroonchik** [comment]
Hello, I would like to start this assignment

**Comment by HarshKapadia2** [comment]
Go ahead, @Haroonchik!

**Comment by Haroonchik** [comment]
@HarshKapadia2  Can you check my PR https://github.com/HarshKapadia2/one-or-two/pull/15 ?
